### ISSUE TITLE
large json files not working

### ISSUE THREAD

**Issue by dtayl20** [weisser-dev/devtools-coverage-extractor#1]
Hi.  Love your online coverage extractor. https://weisser-dev.github.io/devtools-coverage-extractor/  Its great.  I'm having an issue with a large-ish json file 6.3MB.  Works brilliantly on smaller files.  Maybe  I hit a resource limit?  Its a crazy big json file to be pasting into a form ... but its kinda the point ie trying to reduce the amount of css wordpress outputs!!  It would be great if you could find a way to allow bigger files to be processed.  I appreciate any help. Damon

**Comment by dtayl20** [comment]
Hi again. After further testing... I don't think its size.  Maybe the chrome coverage download has some possible formatting irregularities??  Not sure.  It would be great if you could take a look.  Happy to send you copy of my json file that is failing...

**Comment by dtayl20** [comment]
OMG!  LOL... I closed my inconito browser after spending hours working on it.  Opened another incognito browser later that night... bingo it was working.  Key takeaway => restart!!  Brilliant tool!

**Comment by weisser-dev** [comment]
@dtayl20  Sounds great, glad you like my little tool. 
Since no more doing is open, I'll close the ticket. Have fun with the tool. :)
